"""Strategic planner interface, request/answer contracts and offline planners.

The planner chooses one goal from candidates generated by trusted code (control/goals.py);
it never invents targets. Planners return raw text so that every planner, mock or live,
goes through the same parsing, validation, retry and fallback code in the goal manager.
"""

from __future__ import annotations

import json
from typing import Annotated, Any, Protocol

from pydantic import Field, ValidationError

from dave_agent.schemas import Contract, GoalType, Identifier, ModelCallRecord, NonNegInt, TilePos


class GoalCandidate(Contract):
    """One objective the planner may choose. ``route`` is set only for graph-enabled arms."""

    candidate_id: Identifier
    goal_type: GoalType
    target_kind: str  # tile kind (required_item, item, collectible, exit) or explore/recover
    target_name: str
    target: TilePos
    description: str = Field(max_length=200)
    success_predicate: str
    constraints: tuple[str, ...] = ()
    route: dict[str, Any] | None = None
    # Estimated way there over the explored platforms (control/platforms.py), when the adapter
    # has a reach envelope: "c1r9 -jump right-> c4r7 ...", or why no path is known.
    path: str | None = None
    # Items Dave must take first: no path is known without them (e.g. "jetpack": only a flight
    # gets there and Dave has no fuel).
    requires: tuple[str, ...] = ()


class PlanningRequest(Contract):
    """Everything a planner sees. Identical for arms A and B; graph arms add route summaries."""

    episode_id: Identifier
    level_id: Identifier
    frame: NonNegInt
    observation_id: NonNegInt
    triggers: tuple[str, ...]
    player: dict[str, Any]
    lives: int | None
    inventory: dict[str, int] | None
    score: int | None
    view_cols: tuple[int, int]
    nearby: tuple[dict[str, Any], ...]  # visible hazards and monsters near the player
    recent: tuple[dict[str, Any], ...]  # recent executed skills, oldest first
    previous_goal: dict[str, Any] | None  # how the last goal ended
    current_goal: str | None  # target_ref of the goal still active (soft triggers)
    candidates: tuple[GoalCandidate, ...]
    graph_routes: bool
    # The explored level map (control/level_map.py): every screen of this level seen so far.
    map: dict[str, Any] | None = None
    waypoints: tuple[tuple[int, int], ...] = ()  # the active goal's planner waypoints still ahead
    # The explored map as platforms with their exits and reachability (control/platforms.py).
    platforms: tuple[dict[str, Any], ...] = ()
    # What was tried on this level this episode and how it ended; moves that kept failing
    # (control/attempts.py).
    attempts: tuple[dict[str, Any], ...] = ()
    failed_links: tuple[dict[str, Any], ...] = ()

    @property
    def candidate_ids(self) -> tuple[str, ...]:
        return tuple(c.candidate_id for c in self.candidates)


MAX_WAYPOINTS = 5
PlatformId = Annotated[str, Field(pattern=r"^c-?\d+r\d+$")]


class PlanChoice(Contract):
    goal: str = Field(min_length=1, max_length=128)
    rationale: str = Field(default="", max_length=500)
    # Optional intermediate standing tiles [col, row], or platform ids ("c8r4"), on the way to the
    # goal, in order. The goal manager checks each leg with the game's physics before the
    # tactical model follows them.
    waypoints: tuple[tuple[int, int] | PlatformId, ...] = Field(default=(), max_length=MAX_WAYPOINTS)


class PlanOutputError(ValueError):
    """The planner's answer is not a valid choice among the offered candidates."""


def parse_plan(text: str | None, allowed: tuple[str, ...]) -> PlanChoice:
    if not text:
        raise PlanOutputError("empty planner output")
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise PlanOutputError(f"output is not JSON: {exc.msg}") from exc
    try:
        choice = PlanChoice.model_validate(data)
    except ValidationError as exc:
        raise PlanOutputError(f"output does not match {{goal, rationale, waypoints}}: "
                              f"{exc.errors()[0]['msg']}") from exc
    if choice.goal not in allowed:
        raise PlanOutputError(f"goal {choice.goal!r} is not an offered candidate; choose one of {list(allowed)}")
    return choice


class StrategicPlanner(Protocol):
    provider: str
    model: str

    def propose(self, request: PlanningRequest, feedback: str | None = None) -> tuple[str | None, ModelCallRecord]:
        """Return raw output text (None when the call itself failed) and the call record.
        ``feedback`` explains why the previous attempt was rejected."""
        ...


# Fixed objective priority shared by the offline planner and the deterministic fallback.
PRIORITY = {("reach", "exit"): 0, ("collect", "required_item"): 1, ("collect", "item"): 2,
            ("collect", "collectible"): 3, ("explore", "right"): 4, ("explore", "left"): 5,
            ("recover", "recover"): 6}


def priority(candidate: GoalCandidate) -> int:
    key = (candidate.goal_type, candidate.target_name if candidate.goal_type == "explore" else candidate.target_kind)
    return PRIORITY.get(key, len(PRIORITY))


def rule_choice(candidates: tuple[GoalCandidate, ...], avoid: str | None = None) -> GoalCandidate:
    """First candidate by priority, skipping ``avoid`` (a goal that just failed) when possible.
    With path estimates (control/platforms.py), goals with a known path come first. A pick that
    ``requires`` an offered item gives way to that item (the jetpack before a flight-only trophy)."""
    ranked = sorted(candidates, key=lambda c: (bool(c.path and c.path.startswith("no known path")), priority(c)))
    pick = next((c for c in ranked if c.candidate_id != avoid), ranked[0])
    first = next((c for c in ranked if c.goal_type == "collect" and c.target_name in pick.requires), None)
    return first or pick


def _ok(provider: str, model: str) -> ModelCallRecord:
    return ModelCallRecord(provider=provider, model=model, purpose="planner", latency_ms=0.0, status="ok")


class RuleMockPlanner:
    """Offline stub: the fixed priority, avoiding a goal that just failed. No network, no cost."""

    provider, model = "mock", "mock-planner"

    def propose(self, request: PlanningRequest, feedback: str | None = None) -> tuple[str | None, ModelCallRecord]:
        previous = request.previous_goal
        avoid = previous["target_ref"] if previous and previous["status"] != "achieved" else None
        chosen = rule_choice(request.candidates, avoid)
        text = json.dumps({"goal": chosen.candidate_id, "rationale": f"rule priority ({chosen.goal_type})"})
        return text, _ok(self.provider, self.model)


class ScriptedPlanner:
    """Test planner: returns the given outputs in order, then answers like ``RuleMockPlanner``.
    ``None`` simulates a failed call; a callable receives the request and returns the text."""

    provider, model = "scripted", "scripted-planner"

    def __init__(self, outputs: list) -> None:
        self.outputs = list(outputs)
        self.requests: list[PlanningRequest] = []
        self.feedback: list[str | None] = []

    def propose(self, request: PlanningRequest, feedback: str | None = None) -> tuple[str | None, ModelCallRecord]:
        self.requests.append(request)
        self.feedback.append(feedback)
        if not self.outputs:
            return RuleMockPlanner().propose(request, feedback)[0], _ok(self.provider, self.model)
        out = self.outputs.pop(0)
        if callable(out):
            out = out(request)
        if out is None:
            return None, ModelCallRecord(provider=self.provider, model=self.model, purpose="planner",
                                         latency_ms=0.0, status="error")
        return out, _ok(self.provider, self.model)
