"""Game adapter contract. Agents never receive an adapter reference."""

from typing import Protocol, runtime_checkable

from dave_agent.schemas import AdapterCapabilities, Observation, SnapshotRef, StepResult


@runtime_checkable
class GameAdapter(Protocol):
    def capabilities(self) -> AdapterCapabilities: ...
    def reset(self, scenario_id: str, seed: int) -> Observation: ...
    def observe(self) -> Observation: ...
    def step(self, buttons: frozenset[str], frames: int) -> StepResult: ...
    def save_snapshot(self) -> SnapshotRef: ...
    def load_snapshot(self, snapshot: SnapshotRef) -> Observation: ...
    def close(self) -> None: ...


class AdapterError(RuntimeError):
    """Adapter misuse or an unavailable operation."""
